### ISSUE TITLE
Datum Validierung bei den Lernzielen

### ISSUE THREAD

**Issue by PhillippPatzelt** [NicoB-Code/LearnAhead#14]
Aktuell funktioniert die Datums Validierung bei den Lernzielen noch nicht so korrekt.  Es erkennt z.B. bei einem Start und End Datum nicht 100%, dass es ein Datum ist und es müssen folgende Sachen beachtet werden:
**
1. Das Start Datum darf NICHT in der Vergangenheit liegen.
2. Das Ziel Datum darf NICHT früher als das Start Datum sein.
3. Das eingegebene Datum muss Valide sein 
    -> Es erkennt manchmal, dass es kein Datum ist z.B. 3123123.123123.5283452 
    -> Aber ein Datum wie 50.21.2023 erkennt es irgendwie als "valide" **

Vorrübergehend wird in die Validation Funktion in GoalDetailFragment aufgerufen und diese ruft eine DateValidation Funktion auf. Musst ggbf. den Code ein bisschen Refactorn.

**Comment by NicoB-Code** [comment]
Fixed in meinem Branch
